services:
  - type: web
    name: core
    env: python
    buildCommand: "./build.sh"
    startCommand: "daphne -b 0.0.0.0 -p 8000 core.asgi:application"
    disk:
      name: media
      mountPath: /app/media
      sizeGB: 1
