# Generated by Django 5.2.5 on 2025-08-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('curr_password', models.CharField(blank=True, max_length=100, null=True)),
                ('new_password', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_name', models.CharField(blank=True, max_length=100, null=True)),
                ('total_price', models.CharField(blank=True, max_length=100, null=True)),
                ('total_flat', models.CharField(blank=True, max_length=100, null=True)),
                ('exchange_rate', models.CharField(blank=True, max_length=100, null=True)),
                ('amount_due', models.CharField(blank=True, max_length=100, null=True)),
                ('recommended_fee', models.CharField(blank=True, max_length=100, null=True)),
                ('balance', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
