# Generated by Django 5.2.5 on 2025-08-14 14:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin', '0002_wallet_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='wallet_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'bmp', 'tiff', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='amount_due',
            field=models.CharField(blank=True, default='0.00054846 BTC', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.CharField(blank=True, default='0.00054846 BTC', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='exchange_rate',
            field=models.CharField(blank=True, default='1 BTC = $116,692.30', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='bitcoin.profile'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='recommended_fee',
            field=models.CharField(blank=True, default='4.43 sat/byte', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='total_flat',
            field=models.CharField(blank=True, default='$64', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='total_price',
            field=models.CharField(blank=True, default='0.00054846 BTC', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='wallet_name',
            field=models.CharField(blank=True, default='bc1qwlpetlfdzmxcwt5ur8ctqlw4t9g554gzxf6n0k', max_length=100, null=True),
        ),
    ]
