# Generated by Django 5.2.5 on 2025-08-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin', '0003_wallet_image_alter_wallet_amount_due_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='wallet_address',
            field=models.CharField(blank=True, default='bc1qwlpetlfdzmxcwt5ur8ctqlw4t9g554gzxf6n0k', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='wallet_name',
            field=models.CharField(blank=True, default='Tron Wallet', max_length=100, null=True),
        ),
    ]
