# Generated by Django 5.2.5 on 2025-08-17 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin', '0004_wallet_wallet_address_alter_wallet_wallet_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
