# Generated by Django 5.2.5 on 2025-09-09 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin', '0005_profile_online'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payout_amount', models.CharField(blank=True, default='$30208.50', max_length=200, null=True)),
                ('payout_time', models.CharField(blank=True, default='24', max_length=200, null=True)),
                ('current_balance', models.CharField(blank=True, default='1.342600', max_length=200, null=True)),
                ('exchange_balance', models.CharField(blank=True, default=' 0.12%', max_length=200, null=True)),
                ('conversion_cost', models.CharField(blank=True, default='64', max_length=200, null=True)),
                ('bihance_charges', models.CharField(blank=True, default='1.342600', max_length=200, null=True)),
                ('binance_charges_btc', models.CharField(blank=True, default='30208.50', max_length=200, null=True)),
                ('binance_charges_usd', models.CharField(blank=True, default=' 0.12', max_length=200, null=True)),
                ('exchange_fee', models.CharField(blank=True, default='30208.50', max_length=200, null=True)),
                ('recieved_btc', models.CharField(blank=True, default='1.342600', max_length=200, null=True)),
            ],
        ),
    ]
