# Generated by Django 5.2.5 on 2025-09-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin', '0006_pricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='payout_time',
            field=models.CharField(blank=True, default='24 hours', max_length=200, null=True),
        ),
    ]
